require(ggplot2)
library(scales)
blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )
PIE <- read.csv("values_for_r_pie_chart_NRAS_0.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_0.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_NRAS_0.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_NRAS_1.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_1.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_NRAS_1.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_HRAS_2.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_2.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_HRAS_2.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_HRAS_3.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_3.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_HRAS_3.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_4.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_4.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_4.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_5.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_5.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_5.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_6.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_6.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_6.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_7.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_7.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_7.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_8.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_8.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_8.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_9.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_9.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_9.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_10.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_10.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_10.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RAF1_11.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_11.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RAF1_11.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_12.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_12.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_12.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_13.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_13.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_13.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_14.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_14.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_14.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_15.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_15.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_15.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_16.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_16.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_16.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_17.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_17.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_17.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_18.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_18.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_18.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_19.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_19.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_19.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_BRAF_20.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_20.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_BRAF_20.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RASA1_21.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_21.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RASA1_21.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RASA1_22.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_22.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RASA1_22.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RASA1_23.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_23.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RASA1_23.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RASA1_24.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_24.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RASA1_24.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_RASA1_25.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_25.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_RASA1_25.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_CBL_26.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_26.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_CBL_26.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_PTPN11_27.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_27.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_PTPN11_27.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_PTPN11_28.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_28.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_PTPN11_28.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_PTPN11_29.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_29.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_PTPN11_29.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_PTPN11_30.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_30.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_PTPN11_30.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_PTPN11_31.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_31.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_PTPN11_31.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_PTPN11_32.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_32.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_PTPN11_32.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_SPRED1_33.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_33.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_SPRED1_33.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_SPRED1_34.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_34.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_SPRED1_34.png",bg = "transparent", scale=1)
PIE <- read.csv("values_for_r_pie_chart_HRAS_35.csv")
bp<- ggplot(PIE, aes(x="", y=Percentage, fill=Pathway))+geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)+ theme(legend.text = element_text(colour="black", size = 14, face = "bold"),legend.title = element_text(colour="black", size=14, face="bold"))+  blank_theme +theme(axis.text.x=element_blank())+theme(legend.position="bottom") +guides(fill=guide_legend(nrow=4))
#png(file="pie_chart_pathways_35.png",width=300,height=300,units="px", bg="transparent")
ggsave(file="pie_chart_pathways_HRAS_35.png",bg = "transparent", scale=1)
